# Generated by Django 2.2.3 on 2019-07-11 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20190711_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercoupon',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='cart.Cart'),
        ),
    ]
