# Generated by Django 2.2.3 on 2019-07-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_auto_20190714_0724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
